#############################################################################
# Makefile for building: game_michaebq
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Apr 28 02:27:12 2013
# Project:  game_michaebq.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile game_michaebq.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = chess.cpp \
		chessboard.cpp \
		chessboardsquare.cpp \
		chesspiece.cpp \
		chesspiece_bishop.cpp \
		chesspiece_king.cpp \
		chesspiece_knight.cpp \
		chesspiece_pawn.cpp \
		chesspiece_queen.cpp \
		chesspiece_rook.cpp \
		graphicswindow.cpp \
		guipiece.cpp \
		guisquare.cpp \
		mainwindow.cpp moc_graphicswindow.cpp \
		moc_mainwindow.cpp
OBJECTS       = chess.o \
		chessboard.o \
		chessboardsquare.o \
		chesspiece.o \
		chesspiece_bishop.o \
		chesspiece_king.o \
		chesspiece_knight.o \
		chesspiece_pawn.o \
		chesspiece_queen.o \
		chesspiece_rook.o \
		graphicswindow.o \
		guipiece.o \
		guisquare.o \
		mainwindow.o \
		moc_graphicswindow.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		game_michaebq.pro
QMAKE_TARGET  = game_michaebq
DESTDIR       = 
TARGET        = game_michaebq

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: game_michaebq.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile game_michaebq.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile game_michaebq.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/game_michaebq1.0.0 || $(MKDIR) .tmp/game_michaebq1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/game_michaebq1.0.0/ && $(COPY_FILE) --parents chessboard.h chessboardsquare.h chesspiece.h graphicswindow.h guipiece.h guisquare.h mainwindow.h .tmp/game_michaebq1.0.0/ && $(COPY_FILE) --parents chess.cpp chessboard.cpp chessboardsquare.cpp chesspiece.cpp chesspiece_bishop.cpp chesspiece_king.cpp chesspiece_knight.cpp chesspiece_pawn.cpp chesspiece_queen.cpp chesspiece_rook.cpp graphicswindow.cpp guipiece.cpp guisquare.cpp mainwindow.cpp .tmp/game_michaebq1.0.0/ && (cd `dirname .tmp/game_michaebq1.0.0` && $(TAR) game_michaebq1.0.0.tar game_michaebq1.0.0 && $(COMPRESS) game_michaebq1.0.0.tar) && $(MOVE) `dirname .tmp/game_michaebq1.0.0`/game_michaebq1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/game_michaebq1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_graphicswindow.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_graphicswindow.cpp moc_mainwindow.cpp
moc_graphicswindow.cpp: guisquare.h \
		graphicswindow.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h \
		graphicswindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) graphicswindow.h -o moc_graphicswindow.cpp

moc_mainwindow.cpp: graphicswindow.h \
		guisquare.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

chess.o: chess.cpp mainwindow.h \
		graphicswindow.h \
		guisquare.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chess.o chess.cpp

chessboard.o: chessboard.cpp chessboard.h \
		chesspiece.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chessboard.o chessboard.cpp

chessboardsquare.o: chessboardsquare.cpp chessboardsquare.h \
		chessboard.h \
		chesspiece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chessboardsquare.o chessboardsquare.cpp

chesspiece.o: chesspiece.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece.o chesspiece.cpp

chesspiece_bishop.o: chesspiece_bishop.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_bishop.o chesspiece_bishop.cpp

chesspiece_king.o: chesspiece_king.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_king.o chesspiece_king.cpp

chesspiece_knight.o: chesspiece_knight.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_knight.o chesspiece_knight.cpp

chesspiece_pawn.o: chesspiece_pawn.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_pawn.o chesspiece_pawn.cpp

chesspiece_queen.o: chesspiece_queen.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_queen.o chesspiece_queen.cpp

chesspiece_rook.o: chesspiece_rook.cpp chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chesspiece_rook.o chesspiece_rook.cpp

graphicswindow.o: graphicswindow.cpp graphicswindow.h \
		guisquare.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicswindow.o graphicswindow.cpp

guipiece.o: guipiece.cpp guipiece.h \
		graphicswindow.h \
		guisquare.h \
		chessboardsquare.h \
		chessboard.h \
		chesspiece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guipiece.o guipiece.cpp

guisquare.o: guisquare.cpp guisquare.h \
		graphicswindow.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guisquare.o guisquare.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphicswindow.h \
		guisquare.h \
		guipiece.h \
		chesspiece.h \
		chessboard.h \
		chessboardsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_graphicswindow.o: moc_graphicswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicswindow.o moc_graphicswindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

